; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Ä¾Å¼Í¶ÆÁ"
#define MyAppVersion "1.0"
#define MyAppURL "https://pupper.cn"
#define MyAppExeName "PupperScrcpy.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3F9945B3-0CDF-4ED0-8E90-0FAD5ADB8287}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\PupperScrcpy
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=D:\×ÀÃæ
OutputBaseFilename=Ä¾Å¼Í¶ÆÁ-Scrcpy
SetupIconFile=
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\PupperScrcpy\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\adb.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\AdbWinApi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\AdbWinUsbApi.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\avcodec-58.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\avformat-58.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\avutil-56.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\Pupper_side2.ui"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\scrcpy.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\scrcpy-noconsole.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\scrcpy-server"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\SDL2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\swresample-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\swscale-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\PupperScrcpy\logo1.png"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

